import{a as u,S as w}from"./assets/vendor-DS9FuNQt.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const m=document.querySelector(".books-list"),l=document.querySelector(".books-dropdown-menu"),f=document.querySelector(".books-counter"),d=document.querySelector(".show-more-btn"),g=document.querySelector(".dropdown-btn"),p=document.querySelector(".empty-message"),k="https://books-backend.p.goit.global/books/top-books",E="https://books-backend.p.goit.global/books/category-list",C="https://books-backend.p.goit.global/books/category?category";let a=[],i=Math.min(window.innerWidth>=768?24:10,a.length);const S=4;g.addEventListener("click",()=>{l.hidden=!l.hidden});async function q(){try{const e=(await u.get(E)).data,o=document.createElement("li");o.dataset.value="all",o.textContent="All categories",l.appendChild(o),e.forEach(s=>{const t=document.createElement("li");t.textContent=s.list_name,t.dataset.value=s.list_name,l.appendChild(t)})}catch(r){console.log(r.message)}}async function v(r){try{let e=[];if(r==="all"?e=(await u.get(k)).data.flatMap(s=>s.books):e=(await u.get(`${C}=${r}`)).data,a=e,!Array.isArray(e)||e.length===0){m.innerHTML="",p.classList.remove("visually-hidden"),f.textContent="0 books available",d.classList.add("visually-hidden");return}else p.classList.add("visually-hidden");i=i=Math.min(window.innerWidth>=768?24:10,a.length),y(),h(),L()}catch(e){console.log(e.message)}}function y(){m.innerHTML="";const r=a.slice(0,i);m.innerHTML=r.map(({_id:e,book_image:o,title:s,author:t,price:n})=>` <li class="book-list-card">
        <img class="books-card-img" src="${o}" alt="${s}"/>
        <h4 class="books-card-title">${s}</h4>
        <p class="books-card-price">${Math.floor(n)}</p>
        <p class="books-card-author">${t}</p>
        <button class="learn-more-btn" data-book-id="${e}">Learn More</button>    
        </li>
        `).join("")}function h(){f.innerHTML=`Showing ${i} of ${a.length}`}function L(){i>=a.length?d.classList.add("visually-hidden"):d.classList.remove("visually-hidden")}d.addEventListener("click",()=>{i+=S,i>=a.length&&(i=a.length),y(),h(),L()});l.addEventListener("click",P);function P(r){const e=r.target.closest("li");if(!e)return;const o=e.dataset.value;g.textContent=e.textContent,v(o),l.hidden=!0}document.addEventListener("DOMContentLoaded",async()=>{await q(),await v("all")});new w(".feedback-swiper",{slidesPerView:1,spaceBetween:24,loop:!1,autoHeight:!1,observer:!0,observeParents:!0,watchSlidesProgress:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0},breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:3}}});document.addEventListener("DOMContentLoaded",function(){const r=document.querySelector(".footer-subscribe-form"),e=document.getElementById("footer-email-subscribe"),o=document.querySelector(".footer-required-note"),s=document.querySelector(".footer-signup-btn"),t=/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/;function n(){e.value.trim()===""?s.disabled=!0:s.disabled=!1}n(),e.addEventListener("input",n),r.addEventListener("submit",function(c){t.test(e.value)?(o.textContent="* Required field",o.style.color=""):(c.preventDefault(),o.textContent="Please enter a valid email address.",o.style.color="red",e.value="",e.focus(),n())})});document.addEventListener("DOMContentLoaded",function(){const r=document.querySelector(".burger-menu"),e=document.querySelector(".close-navbar-btn"),o=document.querySelector(".navbar-overlay"),s=document.querySelectorAll(".navbar-list a");r.addEventListener("click",()=>{o.classList.add("active"),document.body.classList.add("no-scroll")}),e.addEventListener("click",()=>{o.classList.remove("active"),document.body.classList.remove("no-scroll")}),s.forEach(t=>{t.addEventListener("click",n=>{n.preventDefault();const c=t.getAttribute("href").slice(1),b=document.getElementById(c);b&&b.scrollIntoView({behavior:"smooth"}),o.classList.remove("active"),document.body.classList.remove("no-scroll")})}),window.addEventListener("resize",()=>{window.innerWidth>=768&&o.classList.contains("active")&&(o.classList.remove("active"),document.body.classList.remove("no-scroll"))})});
//# sourceMappingURL=index.js.map
